# Generated by Django 3.2.8 on 2022-01-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0011_rename_date_posted_deletepicture_date_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletePicture',
        ),
    ]
