# Generated by Django 3.2.8 on 2022-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0015_auto_20220106_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfolder',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
