# Generated by Django 3.2.8 on 2022-01-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0017_alter_deletepicture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfolder',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='deletepicture',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='pics.category'),
        ),
    ]
