# Generated by Django 3.2.8 on 2022-01-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0018_auto_20220106_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfolder',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='deletepicture',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='pics.deletedfolder'),
        ),
    ]
