# Generated by Django 3.2.8 on 2022-01-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0019_auto_20220106_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletepicture',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='pics.category'),
        ),
    ]
